Dependencies:
- 'on': ['@all']
  'require':
    'base/png': 'master'
    'base/jpeg': 'master'
    'base/tiff': 'master'
    'base/giflib': 'master'
- 'on': ['Windows']
  'require':
    'base/patch': 'master'
- 'on': ['Windows', 'MacOS', 'Android']
  'require':
    'base/zlib': 'master'
