Dependencies:
- 'on': ['@all']
  'require':
    'base/png': '@same'
    'base/jpeg': '@same'
    'base/tiff': '@same'
    'base/giflib': '@same'
- 'on': ['Windows', 'MacOS', 'Android']
  'require':
    'base/zlib': '@same'
BuildDependencies:
- 'on': ['Windows']
  'require':
    'base/patch': '@same'
