Dependencies:
- 'on': ['@all']
  'require':
    'base/qt': 'master'
- 'on': ['Windows']
  'require':
    'base/patch': 'master'
- 'on': ['Windows', 'MacOS', 'Android']
  'require':
    'base/zlib': 'master'
