PostInstallScripts:
  - 'on': ['@all']
    'require':
      fix-pcfiles: ../tools/make_pkgconfig_files_relocatable.py
  - 'on': ['Windows']
    'require':
      split-debug: ../ci-utilities/split-debug-info.py
      sign-package: ../ci-utilities/sign-windows-package-at-notary-service.py
      verify-no-debug-and-signed: ../ci-utilities/verify-release-binaries.py

Options:
  use-ccache: False
  run-tests: False
  build-tests: False
  run-cppcheck: False
  run-gcovr: False
  use-asan: False
  pkg-config-sanity-check: 'warning'
  macos-rpath-fix: True
  force-build-target: ext_build
  force-install-target: ext_install
