Dependencies:
- 'on': ['Windows']
  'require':
    'base/patch': 'master'
- 'on': ['@all']
  'require':
    'ffmpeg/libogg': 'master'
    'ffmpeg/libvorbis': 'master'
    'base/png': 'master'
- 'on': ['Windows', 'MacOS']
  'require':
    'base/pkgconfig': 'master'
