Dependencies:
- 'on': ['@all']
  'require':
    'base/icu': 'master'
    'base/freetype': 'master'
    'base/png': 'master'
    'base/jpeg': 'master'
- 'on': ['Linux']
  'require':
    'base/tiff': 'master' # can be fetched with pkgconfig only, so not on Windows
    # 'base/webp': 'master' # can be fetched with pkgconfig only, so not on Windows
- 'on': ['Windows']
  'require':
    'base/patch': 'master'
    'base/googleangle': 'master'
    'base/strawberryperl': 'master'
#    'base/jom': 'master' # only for msvc builds
- 'on': ['Windows', 'MacOS']
  'require':
    'base/openssl': 'master' # TODO: do we actually need that on MacOS?
#    'base/pkgconfig': 'master' # supported on linux only
- 'on': ['Android']
  'require':
    'base/openssl': 'master'
- 'on': ['Windows', 'MacOS', 'Android']
  'require':
    'base/zlib': 'master'
Options:
  force-ninja-on-windows: False
