Dependencies:
- 'on': ['@all']
  'require':
    'base/highway': 'master'
    'base/brotli': 'master'
    'base/lcms2': 'master'
    'base/jpeg': 'master'
    'base/png': 'master'
- 'on': ['Windows', 'MacOS', 'Android']
  'require':
    'base/zlib': 'master'