Dependencies:
- 'on': ['@all']
  'require':
    'base/png': 'master'
    'base/icu': 'master'
- 'on': ['Windows']
  'require':
    'base/patch': 'master'
- 'on': ['Windows', 'MacOS']
  'require':
    'base/pkgconfig': 'master'
- 'on': ['MacOS']
  'require':
    'base/zlib':  '@same'
