Dependencies:
- 'on': ['@all']
  'require':
    'ffmpeg/ffmpeg': 'master'
    'ffmpeg/sdl2': 'master'
    'ffmpeg/libvorbis': 'master'
    'base/fftw3': 'master'
    'base/fontconfig': 'master'
- 'on': ['Windows']
  'require':
    'base/patch': 'master'
    'base/dlfcn_win32': 'master'
