Dependencies:
- 'on': ['@all']
  'require':
    'base/qt': '@same'
    'base/extra_cmake_modules': '@same'
- 'on': ['Linux']
  'require':
    'base/wayland-protocols': '@same'
    'base/plasma-wayland-protocols': '@same'
