Dependencies:
- 'on': ['Windows']
  'require':
    'base/patch': 'master'
- 'on': ['@all']
  'require':
    'base/python': 'krita/5.2'
- 'on': ['Linux', 'MacOS']
  'require':
    'base/python-modules': 'krita/5.2'

