Dependencies:
- 'on': ['Windows']
  'require':
    'base/pkgconfig': 'master' # TODO: do we need that? Test on Windows, not needed on Linux
- 'on': ['@all']
  'require':
    'ffmpeg/libogg': 'master'
