Dependencies:
- 'on': ['@all']
  'require':
    'base/qt': '@same'
    'base/extra_cmake_modules': '@same'
    'base/karchive': '@same'
#    'base/libraw': '@same'
    'base/jpegxl': '@same'
#    'base/openexr': '@same' # TODO: openexr is not detected, because 3.0 is required!
#    'base/avif': '@same'
#    'base/heif': '@same'
#TODO: add pkgconfig on windows
