Dependencies:
- 'on': ['@all']
  'require':
    'base/qt': 'master'
    'base/extra_cmake_modules': 'master'
    'base/karchive': 'master'
#    'base/jpegxl': 'master' # disabled due to API breakage in jxl 0.9.0+
#    'base/libraw': 'master'
#    'base/openexr': 'master' # TODO: openexr is not detected, because 3.0 is required!
#                                    openext should not be available on Android armv7-32bit
#    'base/avif': 'master'
#    'base/heif': 'master'
#TODO: add pkgconfig on windows
