Dependencies:
- 'on': ['Windows', 'Linux', 'MacOS', 'Android/x86_64', 'Android/x86']
  'require':
    'base/nasm': '@same'
- 'on': ['Windows']
  'require':
    'base/patch': '@same'
- 'on': ['Windows', 'MacOS']
  'require':
    # on Linux we use meson provided by the distribution
    'base/meson': '@same'
    'base/pkgconfig': '@same'
