Dependencies:
- 'on': ['@all']
  'require':
    'base/expat': '@same'
- 'on': ['Linux']
  'require':
    'base/iconv': '@same'
- 'on': ['Windows']
  'require':
    'base/patch': '@same'
    'base/iconv': '@same'
- 'on': ['Windows', 'MacOS', 'Android']
  'require':
    'base/zlib': '@same'
