Dependencies:
- 'on': ['@all']
  'require':
    'base/freetype': 'master'
    'base/fontconfig': 'master'
    'base/qt': 'master'
    'base/jpeg': 'master'
    'base/png': 'master'
    'base/tiff': 'master'
    'base/boost': 'master'
    'base/lcms2': 'master'
- 'on': ['Windows']
  'require':
    'base/iconv': 'master'
- 'on': ['Windows']
  'require':
    'base/patch': 'master'
