Dependencies:
- 'on': ['@all']
  'require':
    'base/freetype': '@same'
    'base/fontconfig': '@same'
    'base/qt': '@same'
    'base/jpeg': '@same'
    'base/png': '@same'
    'base/tiff': '@same'
    'base/boost': '@same'
    'base/lcms2': '@same'
    'base/iconv': '@same'
- 'on': ['Windows']
  'require':
    'base/patch': '@same'
