Dependencies:
- 'on': ['@all']
  'require':
    'base/python': '@same'
    'base/sip': '@same'
    'base/qt': '@same'
    'base/pyqt5': '@same'
- 'on': ['Linux', 'MacOS']
  'require':
    'base/python-modules': '@same'
