Dependencies:
- 'on': ['Windows']
  'require':
    'base/patch': '@same'
- 'on': ['@all']
  'require':
    'base/python': '@same'
    'base/sip': '@same'
    'base/qt': '@same'
    'base/pyqt5': '@same'

