Dependencies:
- 'on': ['Windows']
  'require':
    'base/patch': 'master'
    'base/strawberryperl': 'master'
- 'on': ['Windows', 'Linux', 'MacOS', 'Android/x86_64', 'Android/x86']
  'require':
    'base/nasm': 'master'
