Dependencies:
- 'on': ['Windows']
  'require':
    'base/patch': '@same'
    'base/strawberryperl': '@same'
- 'on': ['Windows', 'Linux', 'MacOS', 'Android/x86_64', 'Android/x86']
  'require':
    'base/nasm': '@same'
