Dependencies:
- 'on': ['Windows']
  'require':
    'base/patch': 'master'
    'base/iconv': 'master' # on Linux and MacOS ffmpeg uses iconv provided by libc

- 'on': ['@all']
  'require':
    'ffmpeg/flac': 'master'
    'ffmpeg/opus': 'master'
    'ffmpeg/sdl2': 'master'
    'ffmpeg/vpx': 'master'
    'ffmpeg/libvorbis': 'master'
    'ffmpeg/libtheora': 'master'
    'ffmpeg/openh264': 'master'
    'ffmpeg/lame': 'master'
    'heif/libaom': 'master'
    'base/webp': 'master'
    'base/png': 'master'
    'base/jpeg': 'master'

- 'on': ['Windows', 'MacOS']
  'require':
    'base/pkgconfig': 'master'

- 'on': ['Windows', 'MacOS', 'Linux']
  'require':
    'base/lzma': 'master'

- 'on': ['Windows', 'Linux']
  'require':
    'ffmpeg/vpl': 'master'

- 'on': ['Windows', 'MacOS', 'Android']
  'require':
    'base/zlib': 'master'
