Dependencies:
- 'on': ['Windows', 'MacOS', 'Android']
  'require':
    'base/zlib': 'master'
- 'on': ['@all']
  'require':
    'base/jpeg': 'master'
# webp depends on tiff for some reason, so we shouldn't create a cyclic dependency
#    'base/webp': 'master'

