Dependencies:
- 'on': ['@all']
  'require':
    'base/freetype': 'master'
    'base/expat': 'master'
- 'on': ['Windows']
  'require':
    'base/patch': 'master'
- 'on': ['Windows', 'MacOS']
  'require':
    'base/pkgconfig': 'master'
- 'on': ['Windows', 'MacOS', 'Android']
  'require':
    'base/gettext': 'master'
